### PR TITLE
:sparkles: Public pages on landing page

### PR DESCRIPTION
**Pull request by cchampou**
Hi community! Here is a new feature, now the homepage features the link to all users with their Discord avatar.

This way we get instant overview of current users and can head directly to their dashboard.
Before you ask, I've no idea what's happening with some user's avatars, my guess is that recent picture updates has not been hooked by the application yet, probably because it occurred after their last login to the app.

Screenshot 2022-01-29 at 07-30-11 Accountability Dashboard

### CODE REVIEW

**Review by open-longlabs — COMMENTED** [review]
love it!! that's a really good feature which we need so we can see how everyone else is doing. we will review it every sunday on my stream, so its pretty cool and we can help each other reflecting on our performance. like a retrospective scrum meeting. thanks, K_Talpa!

**Review by M123-dev — APPROVED** [review]
Looks good 👍🏼

**Review by Juliotati — APPROVED** [review]
✨

**Comment by duanecreates** [comment]
I like it! Helps everyone to stay more accountable. People are watching. 👀

**Comment by probablyArth** [comment]
🤩🤩

**Review by probablyArth — COMMENTED** [review]
Awesome

**Pull request merged**
